version: '3.8'

services:
  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./certs:/etc/letsencrypt
    depends_on:
      - sanic_app

  sanic_app:
    build:
      context: ./
      dockerfile: sanic/Dockerfile
    ports:
      - "8000:8000"


