version: '3.8'

services:
  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - sanic_app

  sanic_app:
    build:
      context: ./
      dockerfile: sanic/Dockerfile
    ports:
      - "8000:8000"


